name: Hello_pull_request

on:
  pull_request:
  
jobs:
  HelloPRJob:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      shell: pwsh
      run: | 
        Write-Host "hello!"
  UseSecret:
    runs-on: ubuntu-latest
    steps:
    - name: Print SECRET
      shell: pwsh
      env: 
        SECRET1: ${{secrets.SECRET1}}
        SECRET2: ${{secrets.SECRET2}}
      run: | 
        Write-Host "SECRET1:" $env:SECRET1
        Write-Host "SECRET2:" $env:SECRET2
    - name: Print SECRET - script
      shell: pwsh
      env: 
        SECRET1: ${{secrets.SECRET1}}
        SECRET2: ${{secrets.SECRET2}}
      run: ./test.ps1        
  UseSecret-env:
    runs-on: ubuntu-latest
    environment: demo
    steps:
    - name: Print SECRET
      shell: pwsh
      env: 
        SECRET1: ${{secrets.SECRET1}}
        SECRET2: ${{secrets.SECRET2}}
      run: | 
        Write-Host "SECRET1:" $env:SECRET1
        Write-Host "SECRET2:" $env:SECRET2
    - name: Print SECRET - script
      shell: pwsh
      env: 
        SECRET1: ${{secrets.SECRET1}}
        SECRET2: ${{secrets.SECRET2}}
      run: ./test.ps1  
        